var managerOverseer = require('managers_manager.room.economy.overseer');
var managerTasks = require('managers_manager.room.economy.tasks');
var managerSpawner = require('managers_manager.room.economy.spawner');

module.exports = {
    /**
     * Runs all logic for a specific owned room (Colony)
     * @param {Room} room 
     * @param {StructureSpawn} spawn 
     * @param {Creep[]} allCreeps 
     */
    run: function(room, spawn, allCreeps) {
        // 1. Overseer: Analyze the room and set high-level goals/state
        managerOverseer.run(room);

        // 2. Tasks: Generate missions, assign creeps, and request spawns if needed
        managerTasks.run(room);

        // 3. Spawner: Execute spawn requests generated by Tasks
        managerSpawner.run(room);
    }
}
